# -*- coding: utf-8 -*-
"""boston

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zh_L5my550OygUeP5PGLptjiN5IQL81E
"""

import tensorflow as tf
import pandas as pd

# 데이터 준비하기
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
data = pd.read_csv(path)

# print(data.columns) # 컬럼 내용 확인
independent = data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax','ptratio', 'b', 'lstat']]
dependent = data[['medv']]
# print(independent.shape, dependent.shape) # 잘 나누었는지 확인

# 모델 생성
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

from google.colab import drive
drive.mount('/content/drive')

# 데이터로 모델을 학습
model.fit(independent,dependent,epochs=10000 ,verbose=0)
model.fit(independent,dependent,epochs=10)

# 모델을 이용
print(model.predict(independent[0:5]))

# 비교
dependent[0:5]

# 가중치 확인
weights = model.get_weights()


# 학습된 모델
print('medv = ',  end='')
for i in range(len(weights[0])):
  print(weights[0][i][0], end=' * x' + str(i + 1) + ' + ') 
print(weights[1][0])