# -*- coding: utf-8 -*-
"""iris

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMJNSrBPNlyj-cUT8yBsu97W6fVJfJRp
"""

import tensorflow as tf
import pandas as pd

path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
data = pd.read_csv(path)

# 원핫 인코딩
data = pd.get_dummies(data)

independent = data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = data[['품종_setosa', '품종_versicolor','품종_virginica']]

# 모델 생성
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss="categorical_crossentropy", metrics="accuracy")

# 모델을 학습시킴
model.fit(independent, dependent, epochs=500)

# 모델을 이용
type = ['setosa', 'versicolor','virginica'];
for result in model.predict(independent[-5:]):
  print(type[list(result).index(max(result))], end=' ')

# 비교
dependent[-5:]

# 학습한 가중치
model.get_weights()

# list에서 같은 index에 있는 수들로 하나에 식을 만듬