# -*- coding: utf-8 -*-
"""lemonade

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-O3SbBGioXbZFjprnoK-UcHFAU0fdYo
"""

# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 데이터 준비
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
data = pd.read_csv(path);

# 종속변수, 독립변수
independent = data[['온도']]
dependent = data[['판매량']]

# 모델 만들기
x = tf.keras.layers.Input(shape=[1])
y = tf.keras.layers.Dense(1)(x)
model = tf.keras.models.Model(x,y)
model.compile(loss='mse')

# 모델 학습시키기
model.fit(independent,dependent,epochs=10)

# 모델 이용하기
print(model.predict([[15]]))

